# Docker Compose build file: docker-compose -f build.yml build
version: "3.7"

x-common-args: &common-args
  PIHOLE_VERSION: ${PIHOLE_VERSION}
  CORE_VERSION: ${CORE_VERSION}
  WEB_VERSION: ${WEB_VERSION}
  FTL_VERSION: ${FTL_VERSION}

services:
  amd64:
    image: pihole:${PIHOLE_VERSION}-amd64-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-base:${DEBIAN_VERSION:-buster}
  armel:
    image: pihole:${PIHOLE_VERSION}-armel-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:armel-${DEBIAN_VERSION:-buster}-slim
  armhf:
    image: pihole:${PIHOLE_VERSION}-armhf-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:armhf-${DEBIAN_VERSION:-buster}-slim
  arm64:
    image: pihole:${PIHOLE_VERSION}-arm64-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:arm64-${DEBIAN_VERSION:-buster}-slim
  i386:
    image: pihole:${PIHOLE_VERSION}-i386-${DEBIAN_VERSION:-buster}
    build:
      context: .
      args:
        <<: *common-args
        PIHOLE_BASE: pihole/debian-debootstrap:i386-${DEBIAN_VERSION:-buster}-slim